import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout( {children,}: {children: React.ReactNode;}) {
  return (
      <html lang="pl">
      <body style={{ margin: 0, fontFamily: 'sans-serif' }}>
      <nav style={{ padding: '1rem', background: '#f3f4f6', display: 'flex', gap: '1rem' }}>
        <Link href="/" style={{ textDecoration: 'none', fontWeight: 'bold' }}>
          Strona główna
        </Link>
        <Link href="/users" style={{ textDecoration: 'none', fontWeight: 'bold' }}>
          Użytkownicy
        </Link>
      </nav>

      <main className="flex flex-col justify-between items-center mx-auto max-w-5xl p-8 text-center">
        {children}
      </main>
      </body>
      </html>
  );
}
